### ISSUE TITLE
[Compilation] error 4000: Instance of library class [RegisterFilterLib] is not found

### ISSUE THREAD

**Issue by AkumaRRR** [Mattiwatti/EfiGuard#35] opened 2021-06-28 08:19 UTC
> c:\MyWorkspace>build -a X64 -t VS2019 -p EfiGuardPkg/EfiGuardPkg.dsc -b RELEASE
> Build environment: Windows-10-10.0.19041-SP0
> Build start time: 10:14:37, Jun.28 2021
> 
> WORKSPACE        = c:\myworkspace
> EDK_TOOLS_PATH   = c:\myworkspace\basetools
> 
> Processing meta-data .EDK_TOOLS_BIN    = c:\myworkspace\basetools\bin\win32
> CONF_PATH        = c:\myworkspace\conf
> PYTHON_COMMAND   = py -3
> 
> 
> Architecture(s)  = X64
> Build target     = RELEASE
> Toolchain        = VS2019
> 
> Active Platform          = c:\myworkspace\EfiGuardPkg\EfiGuardPkg.dsc
> 
> 
> build.py...
> c:\myworkspace\EfiGuardPkg\EfiGuardPkg.dsc(...): error 4000: Instance of library class [RegisterFilterLib] is not found
>         in [c:\myworkspace\MdePkg\Library\BaseLib\BaseLib.inf] [X64]
>         consumed by module [c:\myworkspace\EfiGuardPkg\EfiGuardDxe\EfiGuardDxe.inf]
> 
> 
> - Failed -
> Build end time: 10:14:37, Jun.28 2021
> Build total time: 00:00:00

**Comment by Mattiwatti** [comment] 2021-06-28 16:13
Hi,

Yes, I was already aware of this and had an unpushed commit to fix this. The problem is that this build failure was caused by a [recent change](https://github.com/tianocore/edk2/commit/1c11e7a2142b1406ccff5e0af0893c94472871c8) in EDK2 master, and that the (actually extremely trivial) fix I had to make for this breaks builds for people who are using a version of EDK2 from *before* the change was made, which is still quite recently.

The current latest EDK2 release [edk2-stable202105](https://github.com/tianocore/edk2/releases/tag/edk2-stable202105) does now contain this change, so I've pushed the fix commit: see 6cd7810. So if you do a `git pull` and try again it should work.

Closing this since I assume it will be fixed for you, but otherwise just reopen and let me know.

**Closed by Mattiwatti** 2021-06-28 16:13 UTC
