### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by yonisoft** [Mattiwatti/EfiGuard#70] opened 2022-11-16 12:47 UTC
nvm

**Comment by yonisoft** [comment] 2022-12-22 22:56
Disable hyper-v or virtual machines from feature on/off windows

**Comment by Mattiwatti** [comment] 2022-12-23 22:05
Closing this as it is a duplicate of #57, however do note that this considered a bug, albeit one that may not be realistically feasible to fix in EfiGuard. I have working PoC versions of a fix for this, but EifGuard is not intended to be a "PoC"-level quality project and as such these fixes have not been merged yet.

**Closed by Mattiwatti** 2022-12-23 22:05 UTC
