### ISSUE TITLE
1.3 version error

### ISSUE THREAD

**Issue by Hiei-YYH** [Mattiwatti/EfiGuard#79] opened 2023-03-29 08:14 UTC
posted in another post and you said it was an older version, well i downloaded the new one and that's what i got:

> Disabling DSE...
> CI!g_CiOptions at 0xFFFFF80765A7D004.
> Failure: NtSetSystemEnvironmentValueEx error 0xC000000D
> The EfiGuard DXE driver is either not loaded in SETVARIABLE_HOOK mode, or it is malfunctioning.
> AdjustCiOptions failed: 0xC000000D

```
`SystemBootEnvironmentInformation:
        - BootIdentifier: {c2a68070-7307-11ec-9677-309c23dc3bad}
        - FirmwareType: UEFI
        - BootFlags: 0x0

SystemModuleInformation:
        - Kernel: ntoskrnl.exe (\SystemRoot\system32\ntoskrnl.exe)

SystemCodeIntegrityInformation:
        - IntegrityOptions: 0x0001
           0x0001: CODEINTEGRITY_OPTION_ENABLED

SystemKernelDebuggerInformation:
        - KernelDebuggerEnabled: 0
        - KernelDebuggerNotPresent: 1

SystemKernelDebuggerInformationEx:
        - DebuggerAllowed: 0
        - DebuggerEnabled: 0
        - DebuggerPresent: 0

SharedUserData->KdDebuggerEnabled: 0x00

SystemKernelDebuggerFlags: 0x00

SystemCodeIntegrityPolicyInformation:
        - Options: 0x40000000
        - HVCIOptions: 0x0000

SystemIsolatedUserModeInformation:
        - SecureKernelRunning: 0
        - HvciEnabled: 0
        - HvciStrictMode: 0
        - DebugEnabled: 0
        - FirmwarePageProtection: 0
        - EncryptionKeyAvailable: 0
        - TrustletRunning: 0
        - HvciDisableAllowed: 0`

```
what can i do?

ps: windows 11 enterprise

**Comment by Mattiwatti** [comment] 2023-03-29 08:29
You have now managed to
- create an issue, and
- post in someone else's unrelated issue

...for something that *already has a currently open issue, with a title that spells out word for word what you are seeing!*

Since you are apparently not willing or not able to read (neither the updated error message, which tells you what the problem is, nor #60, which I told you to read and then post in if you were still having issues), I'm going to close this.

**Closed by Mattiwatti** 2023-03-29 08:29 UTC
