### ISSUE TITLE
BSOD on EfiDSEFix.exe -d

### ISSUE THREAD

**Issue by hassenhamdi** [Mattiwatti/EfiGuard#52] opened 2022-04-20 05:14 UTC
![image](https://user-images.githubusercontent.com/74272600/164267305-9103cd29-df0e-47f8-bd5a-81ae218d8cfb.png)
![image](https://user-images.githubusercontent.com/74272600/164267198-cfeccabc-ff76-4768-97c1-7935e78e0ffa.png)
`Microsoft (R) Windows Debugger Version 10.0.22549.1000 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Windows\Minidump\042022-17359-01.dmp]
Mini Kernel Dump File: Only registers and stack trace are available

Symbol search path is: srv*
Executable search path is: 
Windows 10 Kernel Version 19041 MP (12 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS Personal
Machine Name:
Kernel base = 0xfffff807`2c600000 PsLoadedModuleList = 0xfffff807`2d22a2d0
Debug session time: Wed Apr 20 15:52:59.072 2022 (UTC + 1:00)
System Uptime: 0 days 0:18:53.780
Loading Kernel Symbols
...............................................................
................................................................
................................................................
...............................................
Loading User Symbols
Loading unloaded module list
...........................
For analysis of this file, run !analyze -v
nt!KeBugCheckEx:
fffff807`2c9f73b0 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:fffff687`c6b9e300=000000000000003b
2: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

SYSTEM_SERVICE_EXCEPTION (3b)
An exception happened while executing a system service routine.
Arguments:
Arg1: 00000000c0000005, Exception code that caused the BugCheck
Arg2: fffff80733ac5d80, Address of the instruction which caused the BugCheck
Arg3: fffff687c6b9ec00, Address of the context record for the exception that caused the BugCheck
Arg4: 0000000000000000, zero.

Debugging Details:
------------------

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 2218

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 11759

    Key  : Analysis.Init.CPU.mSec
    Value: 530

    Key  : Analysis.Init.Elapsed.mSec
    Value: 69411

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 86

    Key  : Dump.Attributes.InsufficientDumpfileSize
    Value: 1

    Key  : Dump.Attributes.RequiredDumpfileSize
    Value: 0x6b1fa253

FILE_IN_CAB:  042022-17359-01.dmp

DUMP_FILE_ATTRIBUTES: 0xc
  Insufficient Dumpfile Size
  Kernel Generated Triage Dump

BUGCHECK_CODE:  3b

BUGCHECK_P1: c0000005

BUGCHECK_P2: fffff80733ac5d80

BUGCHECK_P3: fffff687c6b9ec00

BUGCHECK_P4: 0

CONTEXT:  fffff687c6b9ec00 -- (.cxr 0xfffff687c6b9ec00)
rax=fffff80733ac5d80 rbx=fffff687c6b9f680 rcx=fffff687c6b9f680
rdx=fffff687c6b9f948 rsi=0000000000000001 rdi=0000000000000007
rip=fffff80733ac5d80 rsp=fffff687c6b9f608 rbp=fffff687c6b9f6b0
 r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
r11=fffff687c6b9f948 r12=fffff687c6b9f948 r13=ffffbb81c3b67760
r14=fffff687c6b9f680 r15=0000000000000020
iopl=0         nv up ei pl zr na po nc
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00050246
fffff807`33ac5d80 48895c2408      mov     qword ptr [rsp+8],rbx ss:0018:fffff687`c6b9f610=0000000000000020
Resetting default scope

BLACKBOXBSD: 1 (!blackboxbsd)

BLACKBOXNTFS: 1 (!blackboxntfs)

BLACKBOXPNP: 1 (!blackboxpnp)

BLACKBOXWINLOGON: 1

CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  EfiDSEFix.exe

STACK_TEXT:  
fffff687`c6b9f608 fffff807`2cabec82     : 00000000`00000020 fffff687`c6b9f680 ffffbb81`c3b67760 fffff687`c6b9f948 : 0xfffff807`33ac5d80
fffff687`c6b9f610 fffff807`2cab6ec7     : 00000000`00000000 00000000`00000000 00000000`00000000 fffff807`2ce97860 : nt!HalEfiSetEnvironmentVariable+0x5a
fffff687`c6b9f650 fffff807`2ce97881     : fffff687`c6b9f788 00000000`00000000 00000000`001e001c fffff807`2cdc6150 : nt!HalSetEnvironmentVariableEx+0x127
fffff687`c6b9f730 fffff807`2ce968b7     : 00000000`00000020 fffff687`c6b9f831 ffff9382`e02c7710 ffffab07`c324d270 : nt!IopSetEnvironmentVariableHal+0x21
fffff687`c6b9f770 fffff807`2cf4e844     : 00000000`00000020 ffff9382`00000000 fffff687`00000000 00000000`000023f0 : nt!IoSetEnvironmentVariableEx+0x8b
fffff687`c6b9f890 fffff807`2cf5217a     : 00000000`00000010 000000a8`cdaff760 000000a8`cdaff760 00000000`00000000 : nt!ExpSetFirmwareEnvironmentVariable+0x88
fffff687`c6b9f8e0 fffff807`2ca08db5     : 00000000`00000000 00000000`000023f0 00000000`00000000 00007ff7`e1e238b0 : nt!NtSetSystemEnvironmentValueEx+0x22a
fffff687`c6b9f990 00007fff`d1310284     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x25
000000a8`cdaff718 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x00007fff`d1310284

SYMBOL_NAME:  nt!HalEfiSetEnvironmentVariable+5a

MODULE_NAME: nt

IMAGE_NAME:  ntkrnlmp.exe

IMAGE_VERSION:  10.0.19041.1526

STACK_COMMAND:  .cxr 0xfffff687c6b9ec00 ; kb

BUCKET_ID_FUNC_OFFSET:  5a

FAILURE_BUCKET_ID:  AV_nt!HalEfiSetEnvironmentVariable

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {c61e3646-9ef3-fda6-5448-0cc81f8f9e40}

Followup:     MachineOwner`

**Comment by Mattiwatti** [comment] 2022-04-20 09:51
I'm going to need some more info than this.

**Comment by Mattiwatti** [comment] 2022-04-20 23:33
Thanks, much better. Unfortunately I can't reproduce this either on Windows 10.0.19041.1645 or on Windows 11 insider.

You made a screenshot of your recently installed updates - am I assuming correctly that this BSOD didn't occur prior to installing those yesterday? I'd install them myself to check, but they aren't listed on the Windows Update catalog. In fact all I can find about these KBs on Google is threads about people having issues with them... 2 years ago...

If you could post the kernel dump file that'd also be helpful, since currently I can't see what type of fault (read/write/execute) is occurring at the point where the page fault happens.

**Comment by hassenhamdi** [comment] 2022-04-20 23:56
it is the first time using this tools

**Comment by hassenhamdi** [comment] 2022-04-20 23:57
I downoload  it just today

**Comment by hassenhamdi** [comment] 2022-04-21 20:40
[042122-16468-01 - Copie.zip](https://github.com/Mattiwatti/EfiGuard/files/8534920/042122-16468-01.-.Copie.zip)
this is the minidump file I could not find a larger dump

**Comment by hassenhamdi** [comment] 2022-04-24 19:48
did you find a solution for the issues ?

**Comment by Mattiwatti** [comment] 2022-04-26 09:41
> did you find a solution for the issues ?

No.

Your crash dump is **extremely** odd, because it indicates that this is not a page fault as I was expecting it to be (or otherwise perhaps a general protection fault), but rather a 'segment not present fault' (these are named '#NP' in the Intel manual). This is not something that will ever occur in long mode (x64 mode, which is what you were in at the time of the crash) in any normal configuration.

My best guess is that you have some sort of hypervisor running and that it is either buggy, or else injecting the #NP on purpose. This could be something 'benign' such as an antivirus (insofar as AVs can be called benign) or something more sinister/malicious. Again though, this is only a guess. I don't really know what is causing this, but it's the only plausible explanation I can come up with.

**Comment by Mattiwatti** [comment] 2023-03-16 19:43
Any chance you could retry with 2f4a666? See attached if you can't or don't want to compile the driver yourself, since there is no new release with this change yet: [EfiGuardDxe.zip](https://github.com/Mattiwatti/EfiGuard/files/10995223/EfiGuardDxe.zip)

Note that what this commit fixes does not really have anything in common with your issue as far as I can tell, other than being a BSOD while a hypervisor is present, so this is a bit of a stab in the dark.

**Comment by Mattiwatti** [comment] 2023-10-04 15:56
Closing this absent any response and with no way to reproduce, feel free to reopen if you figure out how to reproduce this more reliably.

**Closed by Mattiwatti** 2023-10-04 15:56 UTC
